### ISSUE TITLE
Error when trying to install 

### ISSUE THREAD

**Issue by ar27** [justbuchanan/fontawesome-python#1]
Hi, 
I am getting this error message when trying to install the font. 
Do you think there is a dependency that I am missing? I'm using python 3.4.1.

File "fontawesome\icons.py", line 8
SyntaxError: Non-ASCII character '\xef' in file fontawesome\icons.py on line
 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for detai
ls

Thank you

**Comment by justbuchanan** [comment]
Hmm, I think on most systems, python 3 will interpret source code files as utf-8, which is why I haven't run into this before. It's likely that the default encoding is set differently on your system, which is why you're having problems.

I added `# -*- coding: utf-8 -*-` to the `icons.py` file and uploaded a new version to pypi. Try it out and let me know if that fixes the issue.
